### ISSUE TITLE
define tracking through a drift

### ISSUE THREAD

**Issue by dtabell** [bmad-sim/BeamTracking.jl#4]
element Drift
 - [x] without spin
 - [ ] with spin

**Comment by dtabell** [comment]
Some possible tests:
- [x] low-energy beam
- [x] high-energy beam
- [x] ultra-relativistic beam
- [x] $e^-$, $e^+$, $p^+$, $p^-$
- [x] $\mathcal{M}_D(L) \mathcal{M}_D(L)$ should yield the same result as $\mathcal{M}_D(2L)$
- [x] symmetry checks, _e.g._ $\mathcal{M}_D(-x,-p_x,-y,-p_y,\delta)$
- [x] others ???

**Comment by dtabell** [comment]
I think the addition of spin tracking deserves a separate issue.
So ... closing this one as complete.
