### ISSUE TITLE
implement tracking through a quadrupole

### ISSUE THREAD

**Issue by dtabell** [bmad-sim/BeamTracking.jl#5]
element Quadrupole
 - [x] without spin
 - [ ] with spin

**Comment by dtabell** [comment]
@mattsignorelli I have an initial implementation. see the branch `5-track-symplectic-quad`.
It needs testing, and I have plenty of questions about both type stability and performance.
The former we should address ASAP. The latter we can address later.

In addition, I added two new functions to `utils.jl`: `sincu` and `sinch`.
These also need attention from an expert in type stability.

We should also discuss spin.

**Comment by dtabell** [comment]
Some possible tests:
- [ ] zero strength quad == drift
- [x] low-energy beam
- [x] high-energy beam
- [x] ultra-relativistic beam
- [x] $e^-$, $e^+$, $p^+$, $p^-$
- [ ] symmetry checks, _e.g._ $\mathcal{M}_Q(-x,0,-y,0,\delta)$
- [ ] $+q \text{ in } QD \equiv -q \text{ in } QF$
- [ ] very-short, very-strong quad should look like a thin lens
- [ ] $\mathcal{M}_Q(L) \mathcal{M}_Q(L)$ should yield very nearly the same result as $\mathcal{M}_Q(2L)$
- [ ] the previous comparison should be exact if we use two slices for the latter mapping
- [ ] particles with $q$ some multiple of the elementary charge $e$
- [ ] others ???

**Comment by dtabell** [comment]
The (non-spin) quad is done, and low energy beam tests are done.

**Comment by dtabell** [comment]
Have tests using electrons at energies 5 keV, 1 MeV, and 1 GeV,
and protons at 250 GeV, The electron tests all pass. Still working
on the proton tests.

**Comment by dtabell** [comment]
After I updated to use [AtomicAndPhysicalConstants.jl](https://github.com/bmad-sim/AtomicAndPhysicalConstants.jl), proton tests now pass.

**Comment by dtabell** [comment]
I think the addition of spin tracking deserves a separate issue.
So ... closing this one as complete.
